name: Synchronize website

on:
  push:
    branches:
      "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set new remote
        run: |
          git remote add website https://${{secrets.EXTERNAL_REPOSITORY_PERSONAL_ACCESS_TOKEN}}@github.com/Old-Shatterhand/Old-Shatterhand.github.io.git
      - name: Push changes
        run: |
          git push website main:main
