name: Synchronize website

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Switch from HTTPS to SSH
        run: |
		git remote set-url origin git@github.com:Old-Shatterhand/Old-Shatterhand.github.io.git
	- name: Stage changes
	  run: |
		git add *.css *.html *.json README.md components public
	- name: Commit changes
	  run: |
	    git config user.email "joeres.roman@web.de"
	    git config user.name "Old-Shatterhand"
	    git commit -m "Auto-update of website"
	- name: Push changes
	  uses: ad-m/github-push-action@master
	  with:
	    github-token: ${{ secrets.GITHUB_TOKEN }}
